version: '3'
services:  
  alfresco:    
    environment:
      JAVA_OPTS : "
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=search
        -Dsolr.port=8983
        -Dsolr.secureComms=none
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dalfresco.restApi.basicAuthScheme=true
        -Ddeployment.method=DOCKER_COMPOSE
        -Dcsrf.filter.enabled=false
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        -Dsolr.useDynamicShardRegistration=true
        -Dsearch.solrShardRegistry.purgeOnInit=true
        -Dsearch.solrShardRegistry.shardInstanceTimeoutInSeconds=300
        -Dsearch.solrShardRegistry.maxAllowedReplicaTxCountDifference=1000"
  search:    
    environment:
      - VERSION=${SEARCH_TAG}
    image: quay.io/alfresco/search-services:${SEARCH_TAG}
  