version: "3.7"

services:
  alfresco:
    image: ${ALFRESCO_IMAGE}:${ALFRESCO_TAG}
    environment:
      JAVA_OPTS : "
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=search_slave_load_balancer
        -Dsolr.port=80
        -Dalfresco.protocol=http
        -Dsolr.secureComms=none
        -Dalfresco.secureComms=none
        -Dsolr.baseUrl=/solr-slave
        -Dindex.subsystem.name=solr6
        -Dalfresco.restApi.basicAuthScheme=true
        -Dcsrf.filter.enabled=false
        -Dcors.enabled=false
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"

        -Dtransform.service.enabled=false
        -Dtransform.service.url=
        -Dsfs.url=
        -Dlocal.transform.service.enabled=false
        -DlocalTransform.libreoffice.url=
        -DlocalTransform.tika.url=
        -DlocalTransform.misc.url=
        -DlocalTransform.pdfrenderer.url=
        -DlocalTransform.imagemagick.url=
        "

# Insight Engine or Search Services
  search:
    image: quay.io/alfresco/search-services:${SEARCH_TAG}
    environment:
      #Solr needs to know how to register itself with Alfresco
      - REPLICATION_TYPE=master
      - SOLR_ALFRESCO_HOST=alfresco
      - SOLR_ALFRESCO_PORT=8080
      - REPLICATION_AFTER=commit,startup
      - REPLICATION_CONFIG_FILES=schema.xml,stopwords.txt
      #Alfresco needs to know how to call solr
      - SOLR_SOLR_HOST=search
      - SOLR_SOLR_PORT=8983
      #Create the default alfresco and archive cores
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
      #HTTP by default
      - ALFRESCO_SECURE_COMMS=none
      #Enable Spellcheck by setting to true
      - ENABLE_SPELLCHECK=${SEARCH_ENABLE_SPELLCHECK}
    ports:
      - 8083:8983 #Browser port

  search_slave_load_balancer:
    image: nginx:${NGINX_TAG}
    links:
      - search_slave
    volumes:
      - ./master-slave/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8084:80

  search_slave:
    image: quay.io/alfresco/insight-engine:test
    environment:
      #Replication properties
      - REPLICATION_TYPE=slave
      - REPLICATION_MASTER_HOST=search
      - REPLICATION_MASTER_PORT=8983
      #- REPLICATION_CORE_NAME=${solr.core.name}
      #- REPLICATION_MASTER_PROTOCOL=http
      #- REPLICATION_POLL_INTERVAL=00:00:60
      #Solr needs to know how to register itself with Alfresco
      - SOLR_ALFRESCO_HOST=alfresco
      - SOLR_ALFRESCO_PORT=8080
      #Alfresco needs to know how to call solr
      - SOLR_SOLR_HOST=search
      - SOLR_SOLR_PORT=8983
      #Create the default alfresco and archive cores
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
      #HTTP by default
      - ALFRESCO_SECURE_COMMS=none
    ports:
      - 8983 #Browser port
